In [1]:
import pandas as pd

In [2]:
internacional = pd.read_excel('/Users/matias/Library/CloudStorage/GoogleDrive-mvilla@buenavistacapital.com/.shortcut-targets-by-id/1Lbjcks5sDTC17AftNR6mDxW8bwAA7EaA/BVC/Matias V/Ranking Fondos/Data.xlsx', sheet_name='Internacional fijo')
internacional

,Dates,0JKT LN Equity,AAXJ US Equity,ABCHNSA LX EQUITY,BGFPABA LN EQUITY,CPXJ LN EQUITY,CAFINIV LX EQUITY,FFASAIU LX EQUITY,FFEMASI LX EQUITY,FIASCIU LX EQUITY,...,AEMD GR Equity,EMMUKD SW Equity,HMEM LN EQUITY,JRMD LN Equity,ZEM CN Equity,MXFS LN EQUITY,2520 JP Equity,MANGLOJ ID Equity,PIMCMEI ID Equity,MGHODVH ID Equity
0,2007-01-01,NaN,NaN,NaN,4.13102,NaN,124.47,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2007-01-02,NaN,NaN,NaN,4.17635,NaN,125.69,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-01-03,NaN,NaN,NaN,4.11882,NaN,126.26,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-01-04,NaN,NaN,NaN,4.03831,NaN,125.45,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-01-05,NaN,NaN,NaN,4.05409,NaN,124.76,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5086,2026-06-30,33.03644,164.4093,161.36,30.34479,233.25,467.60,16.25,36.51,22.78,...,105.30114,31.5363,23.6843,52.8335,34.78266,86.670,17.58494,144.74,17.9713,192.83
5087,2026-07-01,33.03644,159.6285,161.36,30.16115,232.74,467.61,16.31,36.01,22.90,...,102.73048,31.1031,23.3617,52.1328,34.78266,85.540,17.62706,144.54,17.9334,192.97
5088,2026-07-02,33.03644,156.9831,156.38,29.12289,235.27,469.65,16.47,34.92,22.93,...,101.19894,30.5870,22.9101,51.2458,33.45209,83.745,17.34567,144.55,17.9713,192.96
5089,2026-07-03,33.03644,156.9831,157.54,29.78165,235.96,471.45,16.67,36.36,23.35,...,104.37032,31.1349,23.5213,52.7307,34.52792,86.030,17.44444,144.55,17.9713,192.96
5090,2026-07-06,33.03644,161.1716,157.54,29.72377,235.73,471.45,16.67,36.36,23.35,...,104.01080,31.1349,23.4568,52.7307,34.34016,85.860,17.41609,144.55,17.9713,192.96

In [3]:
nacional = pd.read_excel('/Users/matias/Library/CloudStorage/GoogleDrive-mvilla@buenavistacapital.com/.shortcut-targets-by-id/1Lbjcks5sDTC17AftNR6mDxW8bwAA7EaA/BVC/Matias V/Ranking Fondos/Data.xlsx', sheet_name='Nacional fijo')
nacional

,Dates,AACCHIA CI Equity,CCHIACB CI Equity,CELFFIB CI EQUITY,CFIMPIO CI EQUITY,CFIQAC CI EQUITY,ECH US EQUITY,FALCTNV CI EQUITY,MBIARANV CI EQUITY,TCHIEQB CI EQUITY,...,CFIETFCC CC Equity,MBIDTANV CI Equity,MORCLPR CI EQUITY,CFIMRCLP CI EQUITY,SECRNOM CI EQUITY,SECR1NV CI EQUITY,FILRDCM CI EQUITY,FALCDCW CI EQUITY,IMTSCLD CI EQUITY,FYDCLAC CI EQUITY
0,2007-01-01,NaN,NaN,33239.7839,2743.7330,NaN,NaN,NaN,24952.7896,NaN,...,NaN,NaN,NaN,5.420810e+03,NaN,NaN,NaN,NaN,NaN,NaN
1,2007-01-02,NaN,NaN,33250.4300,2739.2791,NaN,NaN,NaN,24965.0939,NaN,...,NaN,NaN,NaN,5.459870e+03,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-01-03,NaN,NaN,33408.7278,2751.5267,NaN,NaN,NaN,24926.1817,NaN,...,NaN,NaN,NaN,5.473550e+03,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-01-04,NaN,NaN,33391.5505,2761.7548,NaN,NaN,NaN,25060.9742,NaN,...,NaN,NaN,NaN,5.503620e+03,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-01-05,NaN,NaN,33342.5164,2777.6091,NaN,NaN,NaN,24952.7931,NaN,...,NaN,NaN,NaN,5.506130e+03,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5086,2026-06-30,69973.348,2164.30,90048.6423,25452.0562,135769.5943,57096.02512,5109.5120,107496.3730,2639.91,...,1554.070,17998.3807,21259.55,2.893800e+08,238010.3987,1904.7218,11996.13,1473.284753,1948.9356,1552.7602
5087,2026-07-01,69973.348,2160.90,90048.6423,25522.9903,136011.2290,56982.81593,5112.2888,107888.8395,2634.88,...,1553.658,18011.1875,21262.04,2.894185e+08,238010.3987,1904.7218,12009.03,1474.194439,1952.8696,1553.5011
5088,2026-07-02,70553.057,2155.79,90048.6423,25618.1432,135981.6710,56425.28939,5096.5647,107680.6408,2628.41,...,1554.070,18014.4240,21269.83,2.895292e+08,238010.3987,1904.7218,12003.97,1473.967585,1952.1966,1553.0111
5089,2026-07-03,70489.482,2155.79,90048.6423,25618.1432,135981.6710,56425.28939,5096.5647,107680.6408,2628.41,...,1553.555,18014.4240,21269.83,2.895292e+08,238010.3987,1904.7218,12003.97,1473.967585,1952.1966,1553.0111
5090,2026-07-06,70489.482,2155.79,90048.6423,25618.1432,135981.6710,57307.57256,5096.5647,107680.6408,2628.41,...,1553.555,18014.4240,21269.83,2.895292e+08,238010.3987,1904.7218,12010.13,1473.967585,1952.1966,1553.0111

In [4]:
df_final = pd.merge(internacional, nacional, how = 'left', on = 'Dates')
df_final = df_final.dropna(axis=1, how='all')
df_final

,Dates,0JKT LN Equity,AAXJ US Equity,ABCHNSA LX EQUITY,BGFPABA LN EQUITY,CPXJ LN EQUITY,CAFINIV LX EQUITY,FFASAIU LX EQUITY,FFEMASI LX EQUITY,FIASCIU LX EQUITY,...,CFIETFCC CC Equity,MBIDTANV CI Equity,MORCLPR CI EQUITY,CFIMRCLP CI EQUITY,SECRNOM CI EQUITY,SECR1NV CI EQUITY,FILRDCM CI EQUITY,FALCDCW CI EQUITY,IMTSCLD CI EQUITY,FYDCLAC CI EQUITY
0,2007-01-01,NaN,NaN,NaN,4.13102,NaN,124.47,NaN,NaN,NaN,...,NaN,NaN,NaN,5.420810e+03,NaN,NaN,NaN,NaN,NaN,NaN
1,2007-01-02,NaN,NaN,NaN,4.17635,NaN,125.69,NaN,NaN,NaN,...,NaN,NaN,NaN,5.459870e+03,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-01-03,NaN,NaN,NaN,4.11882,NaN,126.26,NaN,NaN,NaN,...,NaN,NaN,NaN,5.473550e+03,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-01-04,NaN,NaN,NaN,4.03831,NaN,125.45,NaN,NaN,NaN,...,NaN,NaN,NaN,5.503620e+03,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-01-05,NaN,NaN,NaN,4.05409,NaN,124.76,NaN,NaN,NaN,...,NaN,NaN,NaN,5.506130e+03,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5086,2026-06-30,33.03644,164.4093,161.36,30.34479,233.25,467.60,16.25,36.51,22.78,...,1554.070,17998.3807,21259.55,2.893800e+08,238010.3987,1904.7218,11996.13,1473.284753,1948.9356,1552.7602
5087,2026-07-01,33.03644,159.6285,161.36,30.16115,232.74,467.61,16.31,36.01,22.90,...,1553.658,18011.1875,21262.04,2.894185e+08,238010.3987,1904.7218,12009.03,1474.194439,1952.8696,1553.5011
5088,2026-07-02,33.03644,156.9831,156.38,29.12289,235.27,469.65,16.47,34.92,22.93,...,1554.070,18014.4240,21269.83,2.895292e+08,238010.3987,1904.7218,12003.97,1473.967585,1952.1966,1553.0111
5089,2026-07-03,33.03644,156.9831,157.54,29.78165,235.96,471.45,16.67,36.36,23.35,...,1553.555,18014.4240,21269.83,2.895292e+08,238010.3987,1904.7218,12003.97,1473.967585,1952.1966,1553.0111
5090,2026-07-06,33.03644,161.1716,157.54,29.72377,235.73,471.45,16.67,36.36,23.35,...,1553.555,18014.4240,21269.83,2.895292e+08,238010.3987,1904.7218,12010.13,1473.967585,1952.1966,1553.0111

In [5]:
df_final.to_csv('/Users/matias/Desktop/Proyectos/ranking-fondos/data/funds_prices.csv')

In [6]:
diccionario = pd.read_excel('/Users/matias/Library/CloudStorage/GoogleDrive-mvilla@buenavistacapital.com/.shortcut-targets-by-id/1Lbjcks5sDTC17AftNR6mDxW8bwAA7EaA/BVC/Analisis Portafolios/Diccionario Final 2.xlsx')
diccionario.to_csv('/Users/matias/Desktop/Proyectos/ranking-fondos/data/funds_dictionary.csv')

In [7]:
diccionario

,Ticker,Nombre,Moneda,System Asset Class,Portafolio,Asset Class,Geography / Subclass,Market
0,AACCHIA CI EQUITY,ARRAYAN ACCIONES CHILENAS FONDO DE INVERSION,CLP - Chile Peso,RENTA VARIABLE,Nacional,Equities,Chile,Fund
1,ABC CI EQUITY,ABC S.A.,CLP - Chile Peso,RENTA VARIABLE,Nacional,Equities,Chile,Stock
2,BADRT-G,AD RETAIL 2% 2042,CLP - Chile Peso,RENTA FIJA,Nacional,Fixed Income,Chile,Bond
3,BAGRS-D,"AGROSUPER 3,8% 2032",CLF - Chile UF,RENTA FIJA,Nacional,Fixed Income,Chile,Bond
4,BAGRS-L,"AGROSUPER 2,5% 2028",CLF - Chile UF,RENTA FIJA,Nacional,Fixed Income,Chile,Bond
...,...,...,...,...,...,...,...,...
619,IWN US EQUITY,ISHARES RUSSELL 2000 VALUE ETF,USD - United States Dollar,RENTA VARIABLE,Internacional,NaN,NaN,NaN
620,BICE RENTA UF CLASICA,BICE RENTA UF CLASICA,CLP - Chile Peso,RENTA FIJA,Nacional,NaN,NaN,NaN
621,BCHIEF1117,"BANCO DE CHILE 1,8% 2025",CLF - Chile UF,RENTA FIJA,Nacional,NaN,NaN,NaN
622,CHIQ US EQUITY,GLOBAL X FDS MSCICHINA CONSUMER DISCRETIONARY ETF,USD - United States Dollar,RENTA VARIABLE,Internacional,NaN,NaN,NaN
623,CFIFALCSCA.SN,"F. I. FALCOM SMALL CAP CHILE, SERIE A",CLP - Chile Peso,RENTA VARIABLE,Nacional,NaN,NaN,NaN