In [1]:
import pandas as pd

In [2]:
internacional = pd.read_excel('/Users/matias/Library/CloudStorage/GoogleDrive-mvilla@buenavistacapital.com/.shortcut-targets-by-id/1Lbjcks5sDTC17AftNR6mDxW8bwAA7EaA/BVC/Matias V/Ranking Fondos/Data.xlsx', sheet_name='Internacional fijo')
internacional

,Dates,0JKT LN Equity,AAXJ US Equity,ABCHNSA LX EQUITY,BGFPABA LN EQUITY,CPXJ LN EQUITY,CAFINIV LX EQUITY,FFASAIU LX EQUITY,FFEMASI LX EQUITY,FIASCIU LX EQUITY,...,POLGTIU ID Equity,EEM US Equity,XMME GR Equity,AEMD GR Equity,EMMUKD SW Equity,HMEM LN EQUITY,JRMD LN Equity,ZEM CN Equity,MXFS LN EQUITY,2520 JP Equity
0,2007-01-01,NaN,NaN,NaN,4.13102,NaN,124.47,NaN,NaN,NaN,...,NaN,38.0567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2007-01-02,NaN,NaN,NaN,4.17635,NaN,125.69,NaN,NaN,NaN,...,NaN,38.0567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-01-03,NaN,NaN,NaN,4.11882,NaN,126.26,NaN,NaN,NaN,...,NaN,38.3800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-01-04,NaN,NaN,NaN,4.03831,NaN,125.45,NaN,NaN,NaN,...,NaN,37.8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-01-05,NaN,NaN,NaN,4.05409,NaN,124.76,NaN,NaN,NaN,...,NaN,36.7433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4941,2025-12-09,33.03644,125.8422,135.10,20.41243,215.69,504.15,16.19,28.85,23.86,...,185.68,79.8398,74.26922,82.25937,24.4173,18.4971,40.3064,27.31440,67.74,13.78558
4942,2025-12-10,33.03644,127.1305,134.77,20.77972,215.50,502.83,16.20,29.02,23.89,...,188.19,80.7329,74.79482,82.85106,24.4905,18.5680,40.4640,27.52216,67.92,13.92857
4943,2025-12-11,33.03644,126.2897,133.74,20.53413,217.04,504.67,16.25,28.88,23.85,...,187.67,80.3523,74.78178,82.80292,24.6470,18.5747,40.5802,27.45689,68.00,13.97218
4944,2025-12-12,33.03644,124.5947,134.83,20.58105,215.98,507.34,16.27,28.78,23.82,...,179.22,79.4152,73.91489,81.77007,24.4249,18.4161,40.1515,27.15671,67.36,14.07290
4945,2025-12-15,33.03644,124.5947,134.83,20.58105,217.92,507.34,16.27,28.78,23.82,...,179.22,79.4152,74.33176,82.22675,24.5258,18.5005,40.2759,27.15671,67.79,13.88115

In [3]:
nacional = pd.read_excel('/Users/matias/Library/CloudStorage/GoogleDrive-mvilla@buenavistacapital.com/.shortcut-targets-by-id/1Lbjcks5sDTC17AftNR6mDxW8bwAA7EaA/BVC/Matias V/Ranking Fondos/Data.xlsx', sheet_name='Nacional fijo')
nacional

,Dates,AACCHIA CI Equity,CCHIACB CI Equity,CELFFIB CI EQUITY,CFIMPIO CI EQUITY,CFIQAC CI EQUITY,ECH US EQUITY,FALCTNV CI EQUITY,MBIARANV CI EQUITY,TCHIEQB CI EQUITY,...,MODUECH CI EQUITY,MRCLPAE CI Equity,IPSA Index,FIQRLSA CI Equity,FCFIANV CI Equity,IMTDECI CI Equity,MODECHD CI Equity,DEUCORP CI Equity,CFIETFCC CC Equity,MBIDTANV CI Equity
0,2007-01-01,NaN,NaN,33239.7839,2743.7330,NaN,NaN,NaN,24952.7896,NaN,...,NaN,NaN,2693.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2007-01-02,NaN,NaN,33250.4300,2739.2791,NaN,NaN,NaN,24965.0939,NaN,...,NaN,NaN,2689.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-01-03,NaN,NaN,33408.7278,2751.5267,NaN,NaN,NaN,24926.1817,NaN,...,NaN,NaN,2725.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-01-04,NaN,NaN,33391.5505,2761.7548,NaN,NaN,NaN,25060.9742,NaN,...,NaN,NaN,2738.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-01-05,NaN,NaN,33342.5164,2777.6091,NaN,NaN,NaN,24952.7931,NaN,...,NaN,NaN,2723.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4941,2025-12-09,68996.37,1900.49,90048.6423,21147.1562,127398.2596,54348.95238,4943.5553,114184.3254,2458.97,...,1925.3048,21140.87,10179.97,21348.11,1785.2304,1762.5869,1546.9824,50176.4577,1521.408,17357.3162
4942,2025-12-10,68921.62,1901.93,90048.6423,21273.6489,127191.3566,54818.56247,4941.7912,114301.9631,2458.97,...,1924.7423,21147.98,10170.37,21346.71,1785.5079,1762.2783,1546.5132,50176.3312,1525.427,17354.9777
4943,2025-12-11,69787.50,1939.50,90048.6423,21496.1577,129029.9863,55010.59787,5026.3308,115399.8812,2500.67,...,1925.5144,21153.49,10362.86,21350.23,1786.2186,1763.2164,1547.1162,50196.6543,1522.336,17361.5860
4944,2025-12-12,70023.66,1939.50,90048.6423,21695.2526,130149.0756,55417.75117,5061.5365,115399.8812,2500.67,...,1925.5298,21132.92,10400.01,21354.69,1786.8219,1763.2164,1547.1113,50205.9697,1523.881,17361.5860
4945,2025-12-15,70057.50,1939.50,90048.6423,21695.2526,130149.0756,55417.75117,5064.4995,115399.8812,2500.67,...,1925.5298,21132.92,10397.04,21360.73,1787.3456,1763.2164,1547.1113,50220.0818,1524.911,17361.5860

In [4]:
df_final = pd.merge(internacional, nacional, how = 'left', on = 'Dates')
df_final = df_final.dropna(axis=1, how='all')
df_final

,Dates,0JKT LN Equity,AAXJ US Equity,ABCHNSA LX EQUITY,BGFPABA LN EQUITY,CPXJ LN EQUITY,CAFINIV LX EQUITY,FFASAIU LX EQUITY,FFEMASI LX EQUITY,FIASCIU LX EQUITY,...,MODUECH CI EQUITY,MRCLPAE CI Equity,IPSA Index,FIQRLSA CI Equity,FCFIANV CI Equity,IMTDECI CI Equity,MODECHD CI Equity,DEUCORP CI Equity,CFIETFCC CC Equity,MBIDTANV CI Equity
0,2007-01-01,NaN,NaN,NaN,4.13102,NaN,124.47,NaN,NaN,NaN,...,NaN,NaN,2693.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2007-01-02,NaN,NaN,NaN,4.17635,NaN,125.69,NaN,NaN,NaN,...,NaN,NaN,2689.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-01-03,NaN,NaN,NaN,4.11882,NaN,126.26,NaN,NaN,NaN,...,NaN,NaN,2725.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-01-04,NaN,NaN,NaN,4.03831,NaN,125.45,NaN,NaN,NaN,...,NaN,NaN,2738.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-01-05,NaN,NaN,NaN,4.05409,NaN,124.76,NaN,NaN,NaN,...,NaN,NaN,2723.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4941,2025-12-09,33.03644,125.8422,135.10,20.41243,215.69,504.15,16.19,28.85,23.86,...,1925.3048,21140.87,10179.97,21348.11,1785.2304,1762.5869,1546.9824,50176.4577,1521.408,17357.3162
4942,2025-12-10,33.03644,127.1305,134.77,20.77972,215.50,502.83,16.20,29.02,23.89,...,1924.7423,21147.98,10170.37,21346.71,1785.5079,1762.2783,1546.5132,50176.3312,1525.427,17354.9777
4943,2025-12-11,33.03644,126.2897,133.74,20.53413,217.04,504.67,16.25,28.88,23.85,...,1925.5144,21153.49,10362.86,21350.23,1786.2186,1763.2164,1547.1162,50196.6543,1522.336,17361.5860
4944,2025-12-12,33.03644,124.5947,134.83,20.58105,215.98,507.34,16.27,28.78,23.82,...,1925.5298,21132.92,10400.01,21354.69,1786.8219,1763.2164,1547.1113,50205.9697,1523.881,17361.5860
4945,2025-12-15,33.03644,124.5947,134.83,20.58105,217.92,507.34,16.27,28.78,23.82,...,1925.5298,21132.92,10397.04,21360.73,1787.3456,1763.2164,1547.1113,50220.0818,1524.911,17361.5860

In [5]:
df_final.to_csv('/Users/matias/Desktop/Proyectos/ranking-fondos/data/funds_prices.csv')

In [6]:
diccionario = pd.read_excel('dict_temp_full_portfolio.xlsx')
diccionario.to_csv('/Users/matias/Desktop/Proyectos/ranking-fondos/data/funds_dictionary.csv')

In [7]:
diccionario

,Ticker,Asset Class Sistema,Asset Class,Geography / Subclass,Indice,Market
0,0JKT LN EQUITY,RENTA VARIABLE,RENTA VARIABLE,Asia ex-Japan,ISHARES TRUST ISHARES MSCI INDIA ETF,India
1,AAXJ US EQUITY,RENTA VARIABLE,RENTA VARIABLE,Asia ex-Japan,ISHARES MSCI ALL COUNTRY ASIA ES Japan,General
2,ABCHNSA LX EQUITY,RENTA VARIABLE,RENTA VARIABLE,Asia ex-Japan,AB SICAV I CHINA A SHARES EQUITY PORTFOLIO,China
3,BGFPABA LN EQUITY,RENTA VARIABLE,RENTA VARIABLE,Asia ex-Japan,BAILLIE GIFFORD OVERSEAS GROWTH FUNDS ICVC BAI...,General
4,CPXJ LN EQUITY,RENTA VARIABLE,RENTA VARIABLE,Asia ex-Japan,ISHARES MSCI PACIFIC EX Japan UCITS ETF,General
...,...,...,...,...,...,...
611,HMEM LN EQUITY,RENTA VARIABLE,RENTA VARIABLE,Emerging,HSBC MSCI EMERGING MARKETS UCITS ETF,Fund
612,JRMD LN Equity,RENTA VARIABLE,RENTA VARIABLE,Emerging,JPMORGAN GLOBAL EMERGING MARKETS RESEARCH ENHA...,Fund
613,ZEM CN Equity,RENTA VARIABLE,RENTA VARIABLE,Emerging,BMO MSCI EMERGING MARKETS INDEX ETF,Fund
614,MXFS LN EQUITY,RENTA VARIABLE,RENTA VARIABLE,Emerging,INVESCO MSCI EMERGING MARKETS UCITS ETF,Fund
615,2520 JP Equity,RENTA VARIABLE,RENTA VARIABLE,Emerging,NEXT FUNDS EMERGIN MARKET EQUITY MSCI-EM (UNHE...,Fund