In [18]:
import pandas as pd

In [19]:
internacional = pd.read_excel('/Users/matias/Library/CloudStorage/GoogleDrive-mvilla@buenavistacapital.com/.shortcut-targets-by-id/1Lbjcks5sDTC17AftNR6mDxW8bwAA7EaA/BVC/Matias V/Ranking Fondos/Data.xlsx', sheet_name='Internacional fijo')
internacional

,Dates,0JKT LN Equity,AAXJ US Equity,ABCHNSA LX EQUITY,BGFPABA LN EQUITY,CPXJ LN EQUITY,CAFINIV LX EQUITY,FFASAIU LX EQUITY,FFEMASI LX EQUITY,FIASCIU LX EQUITY,...,SSPVEA1 LX EQUITY,STN FP EQUITY.1,STTX IM EQUITY,THNQ US EQUITY,UBSICQC SW EQUITY,UTIURDR ID EQUITY,VERASUR ID EQUITY,WSEENHI ID EQUITY,X71U LN EQUITY,XDAX GR EQUITY
0,2007-01-01,NaN,NaN,NaN,4.13102,NaN,124.47,NaN,NaN,NaN,...,NaN,130.76894,NaN,NaN,NaN,NaN,133.87,NaN,NaN,NaN
1,2007-01-02,NaN,NaN,NaN,4.17635,NaN,125.69,NaN,NaN,NaN,...,NaN,133.22549,NaN,NaN,NaN,NaN,133.87,NaN,NaN,NaN
2,2007-01-03,NaN,NaN,NaN,4.11882,NaN,126.26,NaN,NaN,NaN,...,NaN,131.36312,NaN,NaN,NaN,NaN,136.14,NaN,NaN,NaN
3,2007-01-04,NaN,NaN,NaN,4.03831,NaN,125.45,NaN,NaN,NaN,...,NaN,128.71076,NaN,NaN,NaN,NaN,133.76,NaN,NaN,NaN
4,2007-01-05,NaN,NaN,NaN,4.05409,NaN,124.76,NaN,NaN,NaN,...,NaN,126.06739,NaN,NaN,NaN,NaN,133.60,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,2025-09-23,33.03644,123.6590,131.11,20.03812,218.43,501.81,16.27,28.47,23.56,...,181.04,239.70053,90.94572,65.0300,173.55468,20.6950,520.26,42.4329,9.1265,260.53635
4887,2025-09-24,33.03644,123.2522,132.59,19.98974,215.84,499.77,16.18,28.50,23.52,...,181.04,241.34781,89.80438,64.4800,171.37739,20.6055,524.62,42.3281,9.1265,260.47260
4888,2025-09-25,33.03644,122.8318,133.13,19.88845,214.68,496.91,16.11,28.29,23.42,...,181.04,240.88944,89.70331,63.7000,169.11823,20.4445,525.68,42.0632,9.1028,257.81239
4889,2025-09-26,33.03644,122.1266,131.31,19.76205,215.89,492.63,16.07,27.95,23.31,...,181.04,244.50063,90.23488,63.9000,170.50690,20.0543,513.41,42.3047,9.1283,260.34465
4890,2025-09-29,33.03644,123.3200,131.31,19.91817,218.27,492.63,16.09,28.37,23.43,...,181.04,240.91364,91.05222,64.3448,170.50690,20.0260,520.82,42.3047,9.1543,261.20482

In [20]:
nacional = pd.read_excel('/Users/matias/Library/CloudStorage/GoogleDrive-mvilla@buenavistacapital.com/.shortcut-targets-by-id/1Lbjcks5sDTC17AftNR6mDxW8bwAA7EaA/BVC/Matias V/Ranking Fondos/Data.xlsx', sheet_name='Nacional fijo')
nacional

,Dates,AACCHIA CI Equity,CCHIACB CI Equity,CELFFIB CI EQUITY,CFIMPIO CI EQUITY,CFIQAC CI EQUITY,ECH US EQUITY,FALCTNV CI EQUITY,MBIARANV CI EQUITY,TCHIEQB CI EQUITY,...,CFICOMDP CI EQUITY,CFIETFCC CI EQUITY,DCORPCH CI EQUITY,FALCFIW CI EQUITY,IMTDECI CI EQUITY,IMTSCLI CI EQUITY,MBIRFANV CI EQUITY,MODUECH CI EQUITY,MRCLP CI EQUITY,IPSA Index
0,2007-01-01,NaN,NaN,33239.7839,2743.7330,NaN,NaN,NaN,24952.7896,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2693.36
1,2007-01-02,NaN,NaN,33250.4300,2739.2791,NaN,NaN,NaN,24965.0939,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2689.19
2,2007-01-03,NaN,NaN,33408.7278,2751.5267,NaN,NaN,NaN,24926.1817,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2725.60
3,2007-01-04,NaN,NaN,33391.5505,2761.7548,NaN,NaN,NaN,25060.9742,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2738.99
4,2007-01-05,NaN,NaN,33342.5164,2777.6091,NaN,NaN,NaN,24952.7931,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2723.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,2025-09-23,64502.95,1749.35,90048.6423,18138.8163,113881.5634,48935.37088,4474.8115,106637.3451,2245.53,...,54957.1821,1513.372,54919.3947,1616.16,1745.0538,2414.5739,54962.8447,1898.7715,20871.156,9146.80
4887,2025-09-24,64456.05,1739.06,90048.6423,18175.6054,114401.9016,49066.71082,4472.5688,106909.4961,2239.72,...,54925.3092,1511.723,54878.6987,1615.29,1744.3139,2413.5393,54960.1274,1898.0130,20867.343,9114.79
4888,2025-09-25,64096.77,1720.38,90048.6423,18192.9595,114057.8225,48797.79620,4439.5190,106295.0471,2221.34,...,54913.1732,1512.959,54866.6973,1615.20,1743.8363,2413.2163,54941.0786,1898.0914,20882.300,9040.46
4889,2025-09-26,63880.06,1719.88,90048.6423,18132.1300,113631.1451,48855.37031,4431.4120,106454.9122,2218.43,...,55029.7398,1511.723,54925.3626,1616.81,1745.4285,2416.0776,55000.6806,1899.4228,20871.407,9023.05
4890,2025-09-29,63875.08,1719.97,90048.6423,18131.4175,113615.5678,48577.26435,4430.3983,106441.7791,2218.22,...,55036.4530,1513.268,54933.3446,1617.09,1745.6437,2416.4549,55011.5992,1899.7732,20898.640,8996.57

In [21]:
df_final = pd.merge(internacional, nacional, how = 'left', on = 'Dates')
df_final = df_final.dropna(axis=1, how='all')
df_final

,Dates,0JKT LN Equity,AAXJ US Equity,ABCHNSA LX EQUITY,BGFPABA LN EQUITY,CPXJ LN EQUITY,CAFINIV LX EQUITY,FFASAIU LX EQUITY,FFEMASI LX EQUITY,FIASCIU LX EQUITY,...,CFICOMDP CI EQUITY,CFIETFCC CI EQUITY,DCORPCH CI EQUITY,FALCFIW CI EQUITY,IMTDECI CI EQUITY,IMTSCLI CI EQUITY,MBIRFANV CI EQUITY,MODUECH CI EQUITY,MRCLP CI EQUITY,IPSA Index
0,2007-01-01,NaN,NaN,NaN,4.13102,NaN,124.47,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2693.36
1,2007-01-02,NaN,NaN,NaN,4.17635,NaN,125.69,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2689.19
2,2007-01-03,NaN,NaN,NaN,4.11882,NaN,126.26,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2725.60
3,2007-01-04,NaN,NaN,NaN,4.03831,NaN,125.45,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2738.99
4,2007-01-05,NaN,NaN,NaN,4.05409,NaN,124.76,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2723.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,2025-09-23,33.03644,123.6590,131.11,20.03812,218.43,501.81,16.27,28.47,23.56,...,54957.1821,1513.372,54919.3947,1616.16,1745.0538,2414.5739,54962.8447,1898.7715,20871.156,9146.80
4887,2025-09-24,33.03644,123.2522,132.59,19.98974,215.84,499.77,16.18,28.50,23.52,...,54925.3092,1511.723,54878.6987,1615.29,1744.3139,2413.5393,54960.1274,1898.0130,20867.343,9114.79
4888,2025-09-25,33.03644,122.8318,133.13,19.88845,214.68,496.91,16.11,28.29,23.42,...,54913.1732,1512.959,54866.6973,1615.20,1743.8363,2413.2163,54941.0786,1898.0914,20882.300,9040.46
4889,2025-09-26,33.03644,122.1266,131.31,19.76205,215.89,492.63,16.07,27.95,23.31,...,55029.7398,1511.723,54925.3626,1616.81,1745.4285,2416.0776,55000.6806,1899.4228,20871.407,9023.05
4890,2025-09-29,33.03644,123.3200,131.31,19.91817,218.27,492.63,16.09,28.37,23.43,...,55036.4530,1513.268,54933.3446,1617.09,1745.6437,2416.4549,55011.5992,1899.7732,20898.640,8996.57

In [22]:
df_final.to_csv('/Users/matias/Desktop/Proyectos/ranking-fondos/data/funds_prices.csv')

In [23]:
diccionario = pd.read_excel('dict_temp_full_portfolio.xlsx')
diccionario.to_csv('/Users/matias/Desktop/Proyectos/ranking-fondos/data/funds_dictionary.csv')